Superplanning website V1
UMONS-Cercle-Informatique/superplanning-frontend pull request #6
Opened 2016-12-05 22:19 UTC by edodo7

A first version of Superplanning's website design.

2016-12-05 22:25 UTC, dannywillems commented on app/views/index.scala.html
> +          <p>Tous droits réservés par moi...</p>
:joy:

2017-02-01 20:51 UTC, edodo7 commented
@dannywillems Alors, cette review ?

2017-02-02 11:06 UTC, dannywillems commented on app/Module.java
> +import com.google.inject.AbstractModule;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/Filters.java
> +import javax.inject.*;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/controllers/AsyncController.java
> +package controllers;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/controllers/CountController.java
> +package controllers;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/controllers/HomeController.java
> +package controllers;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/filters/ExampleFilter.java
> +package filters;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/services/ApplicationTimer.java
> +package services;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/services/AtomicCounter.java
> +package services;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on app/services/Counter.java
> +package services;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on test/ApplicationTest.java
> +import java.util.HashMap;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 11:06 UTC, dannywillems commented on test/IntegrationTest.java
> +import org.junit.*;
Tu peux supprimer ce fichier ? Inutile.

2017-02-02 12:22 UTC, dannywillems requested changes

2017-02-02 12:22 UTC, dannywillems commented on app/controllers/HomeController.java
> +package controllers;
Ce fichier ne devait pas être supprimé. Je pensais que tu avais créé un autre controlleur que celui par défaut.

2017-02-02 12:22 UTC, dannywillems commented on conf/routes
> +GET     /count                      controllers.CountController.count
Comme tu as supprimé CountController et AsyncController, cela implique de supprimer les routes qui y mènent. Ca ne compile plus.

2017-02-02 13:48 UTC, dannywillems commented on app/views/main.scala.html
> +<<<<<<< HEAD
T'as oublié :).

2017-02-03 08:40 UTC, dannywillems approved these changes

2017-02-03 08:40 UTC, merged